# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2bf14eff904c319ec961b8fc0e6040491f715dc1659dc3fe0bfb5e6a2148be51b2b2e6505553afe6cdb19c7ba381d768595b3ef71b06b748e5fbd8ce078bbd12

test:
  secret_key_base: 427f8d3f9292a84413b7280fb0d69b0ef3ebafdb142e520371dc04e5b2333945ccb65894e81997cf6e4cb4a2df16e9f668aa82bcac1a9c28bba71b65dab39967

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
